// <auto-generated />
using System;
using Backend.EFCData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Shared.Chat_session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChatTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Chat_sessions");
                });

            modelBuilder.Entity("Shared.Chunks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<int>("PDFId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_l2_ops" });

                    b.HasIndex("PDFId");

                    b.ToTable("Chunks");
                });

            modelBuilder.Entity("Shared.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ConversationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Shared.Conversation_PDF_Chunks", b =>
                {
                    b.Property<int?>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<int?>("PDFChuncksId")
                        .HasColumnType("integer");

                    b.HasKey("ConversationId", "PDFChuncksId");

                    b.HasIndex("PDFChuncksId");

                    b.ToTable("ConversationPdfChunks");
                });

            modelBuilder.Entity("Shared.PDF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("PDFs");
                });

            modelBuilder.Entity("Shared.Chunks", b =>
                {
                    b.HasOne("Shared.PDF", "PDF")
                        .WithMany("PDFChuncks")
                        .HasForeignKey("PDFId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PDF");
                });

            modelBuilder.Entity("Shared.Conversation", b =>
                {
                    b.HasOne("Shared.Chat_session", "ChatSession")
                        .WithMany("Conversations")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Shared.Conversation_PDF_Chunks", b =>
                {
                    b.HasOne("Shared.Conversation", "Conversation")
                        .WithMany("ConversationPDFChunks")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Chunks", "PDF_Chuncks")
                        .WithMany("PDFChunks")
                        .HasForeignKey("PDFChuncksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("PDF_Chuncks");
                });

            modelBuilder.Entity("Shared.PDF", b =>
                {
                    b.HasOne("Shared.Admin", "Admin")
                        .WithMany("PDFs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Shared.Admin", b =>
                {
                    b.Navigation("PDFs");
                });

            modelBuilder.Entity("Shared.Chat_session", b =>
                {
                    b.Navigation("Conversations");
                });

            modelBuilder.Entity("Shared.Chunks", b =>
                {
                    b.Navigation("PDFChunks");
                });

            modelBuilder.Entity("Shared.Conversation", b =>
                {
                    b.Navigation("ConversationPDFChunks");
                });

            modelBuilder.Entity("Shared.PDF", b =>
                {
                    b.Navigation("PDFChuncks");
                });
#pragma warning restore 612, 618
        }
    }
}
